export type JobFunctionVariant =
  | "primary"
  | "accent"
  | "success"
  | "warning"
  | "secondary"
  | "neutral";

export const UNKNOWN_JOB_FUNCTION_CODE = "__unknown";

export const JOB_FUNCTION_LABELS: Record<string, string> = {
  acct: "Accounting / Auditing",
  adm: "Administrative",
  advr: "Advertising",
  anls: "Analyst",
  art: "Art / Creative",
  bd: "Business Development",
  cnsl: "Consulting",
  cust: "Customer Service",
  dist: "Distribution",
  dsgn: "Design",
  edu: "Education",
  eng: "Engineering",
  fin: "Finance",
  genb: "General Business",
  hcpr: "HealthCare Provider",
  hr: "Human Resources",
  it: "Information Technology",
  lgl: "Legal",
  mgmt: "Management",
  mnfc: "Manufacturing",
  mrkt: "Marketing",
  othr: "Other",
  pr: "Public Relations",
  prch: "Purchasing",
  prdm: "Product Management",
  prjm: "Project Management",
  prod: "Production",
  qa: "Quality Assurance",
  rsch: "Research",
  sale: "Sales",
  sci: "Science",
  stra: "Strategy / Planning",
  supl: "Supply Chain",
  trng: "Training",
  wrt: "Writing / Editing",
  [UNKNOWN_JOB_FUNCTION_CODE]: "Unknown",
};

export const JOB_FUNCTION_VARIANT_MAP: Record<string, JobFunctionVariant> = {
  mgmt: "primary",
  stra: "primary",
  genb: "primary",
  bd: "primary",
  cnsl: "primary",
  prjm: "primary",
  prdm: "primary",
  sale: "accent",
  mrkt: "accent",
  advr: "accent",
  pr: "accent",
  art: "accent",
  dsgn: "accent",
  wrt: "accent",
  anls: "success",
  eng: "success",
  it: "success",
  qa: "success",
  sci: "success",
  rsch: "success",
  supl: "warning",
  mnfc: "warning",
  prod: "warning",
  dist: "warning",
  prch: "warning",
  hr: "secondary",
  adm: "secondary",
  cust: "secondary",
  edu: "secondary",
  trng: "secondary",
  hcpr: "secondary",
  acct: "neutral",
  fin: "neutral",
  lgl: "neutral",
  othr: "neutral",
  [UNKNOWN_JOB_FUNCTION_CODE]: "neutral",
};
